#"@com_google_absl//absl/memory",
#"@com_google_absl//absl/time",

cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "@absl//absl/memory",
        "@absl//absl/time"
    ]
)

